### ISSUE TITLE
Cannot find module `node_modules\vite-plugin-sass-glob-import\dist\index.js`

### ISSUE THREAD

**Issue by maximedaoust** [cmalven/vite-plugin-sass-glob-import#1]
This plugin seems exactly what I'm looking for. Unfortunately, the /dist folder doesn't seem to exist, so it's impossible to import the plugin.

**Comment by cmalven** [comment]
@maximedaoust Thank you for flagging this. Looks like I've always been using plugin directly as an ES module so I never even noticed that `dist` wasn't published. That should be fixed now - use version `1.2.0`
