### ISSUE TITLE
Import with ?inline

### ISSUE THREAD

**Issue by finnolav** [cmalven/vite-plugin-sass-glob-import#10]
Globbing inside style.scss when using vites inline query parameter is not working

import cssString from './style.scss?inline'

**Comment by cmalven** [comment]
Unfortunately, this plugin isn't going to try to support every feature offered by Vite - it would significantly complicate the code and I don't have the bandwidth to keep up with the Vite API. It's not even really intended to be used from within Javascript or tested for that use-case.
