### ISSUE TITLE
@import not working since vite 5.0.2 & vite-plugin-sass-glob-import 3.0.0

### ISSUE THREAD

**Issue by MLNOP** [cmalven/vite-plugin-sass-glob-import#12]
Hello,

I've updated my devdependencies today and noticed that a major version of vite is out.
A few things needed to be fixed.

I saw your update for the @import statement inside the vite.config.mjs.
And since this update the glob import don't work anymore.
exemple : @import '../../blocks/**/scss/_block.scss';

**Comment by cmalven** [comment]
@MLNOP I just released 3.0.1 which will hopefully fix this issue. Would you mind trying it out and letting me know if it works for you?

**Comment by MLNOP** [comment]
@cmalven Thanks for the quick reply. 
It works 🥳 but I had to force the install.
I got this error : 
![image](https://github.com/cmalven/vite-plugin-sass-glob-import/assets/16796221/16d8f06f-bafb-436a-b192-d799c26d8a53)

**Comment by cmalven** [comment]
@MLNOP Thank you. 3.0.2 should resolve this, just released.

**Comment by MLNOP** [comment]
@cmalven its working like a charm.
Thanks a lot ;)

**Comment by MLNOP** [comment]
@cmalven its working like a charm.
Thanks a lot ;)

**Comment by cmalven** [comment]
@MLNOP You're welcome and thank you for your patience!
