### ISSUE TITLE
Package needs updated - glob package needs updated

### ISSUE THREAD

**Issue by georgefromohio** [cmalven/vite-plugin-sass-glob-import#15]
Getting warnings from npm that the glob 7.2.3 used isn't supported and needs to be updated to > 9, not sure if everyone is getting this warning.

**Comment by cmalven** [comment]
@georgefromohio Thanks for reporting. I haven't been able to duplicate this using the latest version of Vite and this plugin, so I'll need as much information as possible to help track down what might be going on.

Can you please share your `package.json` and the Node.js version you're using?

**Comment by georgefromohio** [comment]
Thanks for the quick reply... here are a few outputs
```bash
>_ node -v
# v22.8.0
>_ npm install
# npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache # if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
# npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
>_ npm ls inflight glob
# osg-sx@ ~/osg-sx
#└─┬ vite-plugin-sass-glob-import@3.0.2
#  └─┬ glob@7.2.3
#    └── inflight@1.0.6
```
My package.json
```json
{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "axios": "^1.6.4",
        "laravel-vite-plugin": "^1.0.0",
        "sass": "^1.70.0",
        "vite": "^5.3.4",
        "vite-plugin-sass-glob-import": "^3.0.2"
    }
}
```

**Comment by cmalven** [comment]
Thank you very much @georgefromohio. Very helpful. I'll look into it.

**Comment by cmalven** [comment]
@georgefromohio When you have a moment could you please try updating your plugins to `4.0.0-next.1` and let me know if you have any issues?

**Comment by georgefromohio** [comment]
Works beautifully! Thank you for being super responsive and over all great! Appreciate you and your contributions! Will there be a new release? Let me know!

```bash
>_ npm install

# found 0 vulnerabilities
```

**Comment by cmalven** [comment]
@georgefromohio Thanks for testing. Hope to have a release out in the next day.

**Comment by cmalven** [comment]
This was released as https://github.com/cmalven/vite-plugin-sass-glob-import/releases/tag/4.0.0
