### ISSUE TITLE
@import rule not compatible with Dart Sass 3.0.0

### ISSUE THREAD

**Issue by abel-sch** [cmalven/vite-plugin-sass-glob-import#19]
When using this with the latest sass version (1.80.4) I get this deprecation warning concerting the @import rule:

```
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

   ╷
19 │ @import "../../components/blocks/accordion_item/style.scss";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src/scss/styles.scss 19:9  root stylesheet
```

**Comment by cmalven** [comment]
@abel-sch That deprecation warning will be triggered by any use of `@import` whether you're using this plugin or not. If some cases you might be able to use `@use "../../components/blocks/accordion_item/style.scss"` instead, which is supported by this plugin.
