### ISSUE TITLE
Each Sass import created seems to be a file path, not an url.

### ISSUE THREAD

**Issue by maximedaoust** [cmalven/vite-plugin-sass-glob-import#2]
Hi, me again :) 

Currently transformed imports are not in the appropriate output format. 
~~This problem is probably only present for Windows users.~~

Based on sass documentation, 
> To ensure that stylesheets work on every operating system, Sass imports files by URL, not by file path. This means you need to use forward slashes, not backslashes, even when you’re on Windows. 
ref: https://sass-lang.com/documentation/at-rules/import#finding-the-file

Here's the current behavior on Windows :
```
// In src/styles/main.scss
@import "abstracts/**/*.scss";
```
Is transformed to : 
```
@import "C:\myproject\src\styles\abstracts\_variables.scss";
```
The expected behavior would be a relative path :
```
@import "abstracts/_variables.scss"; // or maybe @import "./abstracts/_variables.scss"; 
``` 

Edit : 
The problem is also present on Mac. 

```
@import "Users/myusername/Sites/myproject/abstracts/_variables.scss";
```

**Comment by maximedaoust** [comment]
@cmalven, The solution is probably a combination of `path.relative(mainSassFilePath, partialSassFilePath)` and `.replace(/\\/g, '/')`.

**Comment by cmalven** [comment]
@maximedaoust That's very interesting. I'm not seeing that behavior on my end, on a Mac.

When I import `@import 'files/**/*.scss';` the result for me is: 

```scss
@import "files/_file-a.scss";
@import "files/_file-b.scss";
```

This is true both when running the automated test suite and when examining the processing in use on an actual site using https://github.com/antfu/vite-plugin-inspect

I trust that what you're seeing is actually occurring, but I'm not sure what would explain for the difference, at least on a Mac. I can look into this but it might take me awhile to get to it.

**Comment by maximedaoust** [comment]
Thanks again for the quick reply.

Oh that's weird. Personnally, i've done my tests on Windows, but I've ask a Mac coworker to test it out just to be sure. Same behavior except the backslach.  

On my end, on Windows, the problem seem to be caused by the following lines : 
```
   // vite-plugin-sass-glob-import/dist/index.js line 65-66
   
   // Initially filename equals "C:/myproject/src/styles/abstracts/_variables.scss"
  filename = path.normalize(filename).replace(basePath, "");  
  // After the normalize and the replace, it equal C:\myproject\src\styles\abstracts\_variables.scss  
  // Normalize switch fowardslaches to backslashes and then the replace don't occur because of the backslashes
  filename = filename.replace(/^\//, "");
```

So here's what I would suggess to fix the issue, replace theses two lines with the following : 
```
  filename = path.relative(basePath, filename).replace(/\\/g, '/');
```  
Let me know if the behavior is the same as expected.

**Comment by cmalven** [comment]
Thanks @maximedaoust that seems to work on my end. Can you please test using `1.2.1` and see if this resolves your issues?

**Comment by maximedaoust** [comment]
Yeah the issue is resolved !! 🎉

**Comment by cmalven** [comment]
@maximedaoust Woohoo! Thanks for your help.
