### ISSUE TITLE
Vite 6 support?

### ISSUE THREAD

**Issue by groenroos** [cmalven/vite-plugin-sass-glob-import#22]
The peer dependency for `vite` set at `^5.0.0` is preventing us from upgrading to Vite 6. Is there anything (beyond updating the `peerDependencies`) that needs to be done to make this plugin compatible with Vite 6?

**Comment by cmalven** [comment]
Currently in testing. Stay tuned.

**Comment by cmalven** [comment]
https://github.com/cmalven/vite-plugin-sass-glob-import/releases/tag/5.0.0
