### ISSUE TITLE
npm package lists wrong URL for this repo

### ISSUE THREAD

**Issue by jrochkind** [cmalven/vite-plugin-sass-glob-import#6]
Took me a while to find this repo! The npm package listing:

https://www.npmjs.com/package/vite-plugin-sass-glob-import

Lists homepage and repository URLs that are wrong, it lists `https://github.com/cmalven/vite-plugin-glob-import`, which just 404s. Which made it hard for me to find this repo, which didn't google well either! Eventually I realized `cmalven` was still there, and looked around at your other repos. 

I guess that's just from this one line in package.json?

https://github.com/cmalven/vite-plugin-sass-glob-import/blob/2cad5760491f7e341c12b1575f8c96881e4754ac/package.json#L23

Thanks for the plugin, it's helpful!

**Comment by cmalven** [comment]
Thank you for calling this to my attention @jrochkind! This has been corrected in https://github.com/cmalven/vite-plugin-sass-glob-import/releases/tag/1.4.0
